FROM python:3.8-slim-buster

WORKDIR ./src/urllookup

COPY src/requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

#CMD ["uvicorn","src.urllookup:urlapp", "--host", "0.0.0.0", "--port", "8091"]
CMD [ "python3", "./src/urllookup.py"]

