FROM python:3.8-slim-buster

WORKDIR ./src/urlupdate_v1

COPY src/requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

#CMD ["uvicorn","src.urlupdate:urlupdate", "--host", "0.0.0.0"]
CMD [ "python3", "./src/urlupdate.py"]

